{{- range $name, $service := .Values.services }}
{{- if and $service.enabled $service.externalSecret $service.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}-secrets
spec:
  refreshInterval: {{ $.Values.global.externalSecrets.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ $.Values.global.externalSecrets.secretStore | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ $name }}-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ printf "%s/%s/%s" $.Values.global.externalSecrets.pathPrefix $.Values.environment $name | quote }}
{{- end }}
{{- end }}
