{{- range $name, $service := .Values.services }}
{{- if and $service.enabled $service.ingress $service.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: {{ $service.ingress.tls | default false | quote }}
spec:
  ingressClassName: nginx
  {{- if $service.ingress.tls }}
  tls:
    - hosts: [{{ $service.ingress.host | quote }}]
      secretName: {{ $service.ingress.tlsSecret | default (printf "%s-tls" $name) }}
  {{- end }}
  rules:
    - host: {{ $service.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port: { number: 80 }
{{- end }}
{{- end }}
