apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wellpass-environments
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: sit
          - env: uat
          - env: prod
  template:
    metadata:
      name: wellpass-{{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/andersonmarquesgit/wellpass-infra.git
        targetRevision: main
        path: charts/wellpass
        helm:
          releaseName: wellpass
          valueFiles:
            - ../../environments/common.yaml
            - ../../environments/{{env}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: wellpass-{{env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
