apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wellpass-platform-environments
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            cluster: wellpass-non-prod
          - env: sit
            cluster: wellpass-non-prod
          - env: uat
            cluster: wellpass-non-prod
          - env: prod
            cluster: wellpass-prod
  template:
    metadata:
      name: wellpass-platform-{{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/andersonmarquesgit/wellpass-infra.git
        targetRevision: main
        path: platform/overlays/{{env}}
      destination:
        name: '{{cluster}}'
        namespace: wellpass-{{env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
