name: Receive application image
on:
  repository_dispatch:
    types: [wellpass-image]
permissions:
  contents: write
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Promote commit tag to dev
        env:
          TAG: sha-${{ github.event.client_payload.sha }}
        run: sed -i -E "s/tag: sha-[A-Za-z0-9_-]+/tag: $TAG/g" environments/common.yaml
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "deploy(dev): wellpass ${{ github.event.client_payload.sha }}"
